---
name: Populate Renovate resources
on:
  pull_request:
    branches:
      - main
permissions:
  contents: write
  id-token: write # needed for keyless signing
jobs:
  resources:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'renovate[bot]' }}
    steps:
      - name: Clone repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Configure gitsign
        uses: chainguard-dev/actions/setup-gitsign@0cda751b114eb55c388e88f7479292668165602a # v1.0.2

      - name: Install tools
        uses: ./.github/actions/install-tools

      - name: Update checksum
        env:
          GH_TOKEN: ${{ github.token }}
        if: ${{ !startsWith(github.ref, 'refs/heads/renovate/') }}
        run: |-
          ./.github/hack/update.sh

          ./.github/hack/zarf.sh

          # git push if we have a diff
          if [[ `git status --porcelain=1 | wc -l` -ne 0 ]]; then
            git add .
            git config --global user.email "<29139614+renovate[bot]@users.noreply.github.com>"
            git config --global user.name "renovate[bot]"
            git commit -am "chore(resources): updated resources files"
            git push origin HEAD:${{ github.head_ref }}
          fi

  test-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Install tools
        uses: ./.github/actions/install-tools

      - name: Start oci registry
        working-directory: .github/hack
        run: |
          docker compose -f docker-compose.yml up -d

      - name: Package Zarf package, amd64
        run: |-
          zarf package create --confirm . --architecture amd64

      - name: Publish Zarf package, amd64
        run: |-
          zarf package publish zarf-*-amd64-*.zst oci://localhost:5202/${{ github.repository_owner }} --plain-http

      - name: Package Zarf package, arm64
        run: |-
          zarf package create --confirm . --architecture arm64

      - name: Publish Zarf package, amd64
        run: |-
          zarf package publish zarf-*-arm64-*.zst oci://localhost:5202/${{ github.repository_owner }} --plain-http

      - name: Publish Zarf package, skeleton
        run: |-
          zarf package publish . oci://localhost:5202/${{ github.repository_owner }} --plain-http
